### ISSUE TITLE
【PaddlePaddle Hackathon 2】114、PaddleSpatial添加时间序列预测模块

### ISSUE THREAD

**Issue by zhoujingbo** [PaddlePaddle/PaddleSpatial#10]
（此 ISSUE 为 PaddlePaddle Hackathon 第二期活动的任务 ISSUE，更多详见 https://github.com/PaddlePaddle/Paddle/issues/40234）

【任务说明】
任务标题： PaddleSpatial添加路时间序列预测模块
技术标签：Python、 PaddlePaddle
任务难度：简单
详细描述：实现最新的时间序列预测算法，完善PaddleSpatial时间序列预测能力
包括：1） 基于RNN的时序预测（非常简单）
           2）论文 Informer: Beyond Efficient Transformer for Long Sequence Time-Series Forecasting (AAAI'21 Best Paper)
【提交流程】
直接PR至 https://github.com/PaddlePaddle/PaddleSpatial/tree/main/paddlespatial/modelzoo/timeseries即可开启验收。
【提交内容】
相关模块源代码、开发文档、Benchmark。
【合入标准】
开发完成，并参与后续维护至正式版本发布。
【技术要求】
熟悉PaddlePaddle基本算法模块。
【参考内容】
informer：https://github.com/zhouhaoyi/Informer2020 包含informer的实现代码；
Seq2Seq:https://github.com/LibCity/Bigscity-LibCity/blob/master/libcity/model/traffic_speed_prediction/Seq2Seq.py  
 中含有一个RNN做时间序列预测的示例。
【答疑交流】
如果在开发中对于上述任务有任何问题，欢迎在本 ISSUE 下留言交流。
对于开发中的共性问题，在活动过程中，会定期组织答疑，请大家关注官网&QQ群的通知，及时参与。

**Comment by xiaoyangyang2** [comment]
您好，请问下Informer是需要前向对齐就可以，还是说精度也需要对齐
