### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by yuwoyizhan** [PaddlePaddle/PaddleSpatial#14]
1.我虽然看不懂英文,但我通过百度搜索Informer: Beyond Efficient Transformer for Long Sequence Time-Series Forecas,看到了很多关于该篇论文的解读,主要就是作者认为Transformer用于长时间序列预测研究潜力很大,但目前存在3个问题,分别提出了解决办法,并且效果验证还不错.可是论文很多东西没有涉及.
比方说,论文采用官方数据集这种方式进行模型效果验证,这样一来,因变量y由几个自变量x决定,已经由数据集定义好了,可是现实生活中不是这样的.为了通过多维x预测y,我们首先得确定哪些维度x会影响y.我想问问,假设我为了预测一个变量y,我通过实验或者某种方法,得到了100维自变量的数据和因变量y的数据,但我如何通过一个算法或者模型,判断哪些维度的自变量x是关于y的有效自变量,哪些维度的自变量x是关于y的无效自变量.比如为了预测引力,我得到了物体质量,体积这2个维度的数据和重力数据,我如何通过一个算法或者模型,得到引力只跟质量有关,跟体积无关这个结论?我又如何通过模型,得到引力不仅仅跟质量有关,还跟某个或某些未知自变量有关的结论?(注:引力=[引力常量]乘以两物体质量的[乘积]除以它们距离的平方。)
希望百度paddlespatial可以提供这个模型或者算法,谢谢.这对我很重要.
2.时间序列预测,在我看来分为两类,一类是短时间时间预测序列,比如根据过去值,预测未来一天的值.听过多数论文都是研究短时间时间预测序列.这种短时间时间序列预测是重中之重,希望可以提供很多模型.比如clas图像分类就提供了不下于100个模型.上面那篇论文提到的似乎属于长时间时间预测序列.我经常听说长时间预测序列并不靠谱,根据过去很长一段时间的天气温度,湿度等变量,预测30天后的天气温度?这不扯淡一样吗?
不知道现在技术如何了,真能做到长时间序列预测吗?
扯远了,我想说的是,对于时间预测序列,我应该使用过去多长时间的数据去训练,去预测.比如预测天气,我应该使用过去一年,过去一月,还是过去一周的数据进行模型训练和预测呢?目前好像没有人提供这种模型,告诉我应该选择过去多久的数据进行训练和预测.
希望百度paddlespatial可以提供这个模型或者算法,谢谢.这对我很重要.
3.上个问题,我认为你们回答了一半吧.通过issue交流很不方便,我也知道罗马帝国不是一天建成的,paddlespatial肯定也不是短时间可以取得巨大成功.希望你们可以多复现那些SOTA算法,无论短时间时间序列预测还是长时间时间序列预测.其实在我看来,短时间时间序列预测和长时间时间预测序列应该使用不同的模型算法,不知道你们认为如何.
4.能加个QQ聊聊吗?issue太不方便了,微信也行,拜托.QQ:1226194560   微信:18820785964

**Comment by zhoujingbo** [comment]
已请求加微信哈，请通过下，谢谢。
