### ISSUE TITLE
Package Requirements for WPF

### ISSUE THREAD

**Issue by q3erf** [PaddlePaddle/PaddleSpatial#157]
hi, we want to try the model ensemble of machine learning models and deep learning models. Could you install lightgbm==3.3.2 in the pytorch environment? thx!

**Comment by ramber1836** [comment]
This was added to the PyTorch environment. Please refer to the pre-installed packages in the PyTorch environment in the Evaluation Manual.

**Comment by q3erf** [comment]
oh, I just found that, thanks!
