### ISSUE TITLE
kddcup22-sdwpf-evaluation提交结果报错

### ISSUE THREAD

**Issue by miraclefish** [PaddlePaddle/PaddleSpatial#281]
在此次比赛中，我们队伍的提交结果总是提示 Error occurred：Err: Accuracy (-0.004) is lower than Zero, which means that the RMSE (in latest 24 hours) of the 120...

因为 Err 显示不完全，我们并不清楚是哪里产生了错误，导致无法得到测试结果的分数。

我们在本地运行 evaluation.py 是完全可以跑通的，没用任何报错，可否提供远程服务器完整的报错信息？

**Comment by ramber1836** [comment]
As we announced right before the 3rd phase competition, the questions on the technical errors will not be answered in Phase 3. These technical errors should be Q&A during the 2nd phase competition. 
Sorry for that.
