### ISSUE TITLE
I wonder whether there will be a preprocessing py and it prompted that you must implement the backward function for custom autograd.Function

### ISSUE THREAD

**Issue by phet1113** [PaddlePaddle/PaddleSpatial#301]
Hello, I want to ask whether the author can provide preprocessing code, otherwise it is difficult to reproduce the corresponding results. In addition, I put wind.csv into data folder and found that it prompted that you must implement the backward function for custom autograd.Function

**Comment by ramber1836** [comment]
There is no special preprocessing for the benchmark datasets adopted in our work. For the synthetic data, the implementation details are already provided in the paper. 
For your second question, you should make sure that all the dependencies are added to your environment.
