### ISSUE TITLE
Reproducibility of D3VAE

### ISSUE THREAD

**Issue by brunorigal** [PaddlePaddle/PaddleSpatial#303]
Hi, I have been trying to reproduce the results published in the paper [D3VAE](https://arxiv.org/abs/2301.03028), with the following command:
```
python main.py       --root_path ~/data/ETDataset-main/ETT-small --data_path ETTh1.csv \
                     --input_dim 7 --percentage 0.05 --diff_steps 1000 \
                     --beta_end 0.1
```

The last lines I got were:
```
mse:0.3795701265335083, mae:0.4926460385322571
0.4403777 0.0682598 0.5076214 0.040027253
```
If I understand well, 0.4403777 is the average mse over several runs of the experiment. But I do not find this value in the paper rather the value indicated is 0.292. 

Is there something I am missing?

**Comment by ramber1836** [comment]
Hi there, 

Which version did you test?

**Comment by brunorigal** [comment]
I just cloned your repo, and ran the script on the master branch.

**Comment by brunorigal** [comment]
Yes I did follow the readme  (in the pytorch repo) and the command I used was copy pasted from this very readme. Am I getting the wrong result or is it my interpretation of the printed results which is wrong?

**Comment by timm-gatg** [comment]
I am having the same issue (pytorch), the MSE / MAE (=CRPS) values I get with the commands mentioned in the README file differ quite significantly from the values reported in the paper

Wind
Mine: MSE | MAE
0.998 +- 0.091 | 0.696 +- 0.072
Paper MSE | MAE
0.681 +- 0.075 | 0.596 +- 0.052

ETTh1
Mine: MSE | MAE
0.354 +- 0.051 | 0.450 +- 0.032
Paper MSE | MAE
0.292 +- 0.036 | 0.424 +- 0.033

ETTm1
Mine: MSE | MAE
1.134 +- 0.162 | 0.860 +- 0.074
Paper MSE | MAE
0.527 +- 0.073 | 0.557 +- 0.048

**Comment by timm-gatg** [comment]
If I adjust the params for the ETT runs with described in the paper, at least the ETTh1 becomes closer to the values reported in the paper:

ETTh1 MSE | MAE (better)
0.321 +- 0.033 | 0.426 +- 0.022

ETTm1 MSE | MAE (worse)
1.156 +- 0.092 | 0.878 +- 0.049

(params added --psi 0.05 --lambda1 0.1 --gamma 0.001 )

**Comment by yl4467** [comment]
hi, The result of the code run directly by the command in the readme is the result of the predicted length of 16.
ETTh1:
MSE|MAE
0.374|0.488

ETTm1:
0.968|0.821

besides, '--sequence_length' and '--prediction_length' need to be set as 8 to get the results of prediction 8.

**Comment by BenjiKCF** [comment]
Successfully replicate the ETTh1 16 result.
```
                    --data_path data/ETTh1.txt \
                    --input_dim 7 \
                    --beta_end 0.1 --gpu 0 \
                    --sequence_length 16 --prediction_length 16 --patience 5  \
                    --percentage 0.05 --diff_steps 1000 \
                    --psi 0.05 --lambda1 0.1 --gamma 0.001
```
