### ISSUE TITLE
D3VAE number of disentanglement factors?

### ISSUE THREAD

**Issue by timm-gatg** [PaddlePaddle/PaddleSpatial#304]
Hi, the paper states in 3.1 implementation details:
"The number of disentanglement factors is chosen from {4, 8}"

However, I don't see an option to configure that in the provided python code (both the paddlepaddle and the pytorch based ones). Is that option named differently or is that hard-coded somewhere?

**Comment by yl4467** [comment]
Hi, the '--num_latent_per_group' decides the number of disentanglement factors.
