### ISSUE TITLE
D3VAE: overwrites timestamps?

### ISSUE THREAD

**Issue by timm-gatg** [PaddlePaddle/PaddleSpatial#307]
Hi,

I came across something weird in the D3VAE code. In data_loader.py, line 93, you just manually overwrite the timestamps of the data:

`df_stamp = pd.date_range(start='4/1/2018',periods=border2-border1, freq='H')`
`data_stamp = time_features(df_stamp, timeenc=self.timeenc, freq=self.freq)`

Can you tell me why that is?

**Comment by yl4467** [comment]
hi,
This is to read in some data sets with irregular time formats. We have tested that this operation does not affect the experimental results.
