### ISSUE TITLE
Questioning the validity of the diffusion module

### ISSUE THREAD

**Issue by PLUTO-SCY** [PaddlePaddle/PaddleSpatial#311]
I have run the pytorch version code and found a unreasonable result: I set the parameter _"diff_steps"_ to 0, 10, 50, 100, 200, 500, 1000, then run the code in ETTh1 and  wind datasets. What I find is that , as the number of diffusion steps increases, the results are getting worse. (Both mse and mae are). Below is the result record I run on ETTh1.  I also turn the mse result into a picture (at the end of this issue). So I doubt the validity of the diffusion module.

```python

dataset name: ETTh1
prediction_length: 8
diff_steps: 0
mse mean:0.24760339
mse std:0.020427
mae std:0.3878688
mae std:0.017404405

dataset name: ETTh1
prediction_length: 8
diff_steps: 10
mse mean:0.26035553
mse std:0.012089639
mae std:0.39704275
mae std:0.017935857

dataset name: ETTh1
prediction_length: 8
diff_steps: 50
mse mean:0.26268333
mse std:0.0169106
mae std:0.40157977
mae std:0.015663896

dataset name: ETTh1
prediction_length: 8
diff_steps: 100
mse mean:0.281945
mse std:0.06063651
mae std:0.41526827
mae std:0.051474944

dataset name: ETTh1
prediction_length: 8
diff_steps: 200
mse mean:0.26382175
mse std:0.03267344
mae std:0.39231223
mae std:0.028107507

dataset name: ETTh1
prediction_length: 8
diff_steps: 500
mse mean:0.363977
mse std:0.06955655
mae std:0.45770007
mae std:0.048627686

dataset name: ETTh1
prediction_length: 8
diff_steps: 1000
mse mean:0.35823375
mse std:0.05329487
mae std:0.4454666
mae std:0.032828197
``` 
![wind-length16](https://user-images.githubusercontent.com/78310004/230750463-208b4801-ae06-4c65-81b3-3b1506b0de78.jpg)
![ETTh1-length8](https://user-images.githubusercontent.com/78310004/230750470-13dff055-0d89-4e9e-b722-9e34700d43d4.jpg)

**Comment by ramber1836** [comment]
Thanks for your question. 
Please refer to our paper's discussions (Section F in the Appendix). 
When larger diffusion steps or a wider variance schedule is employed, the diffused series deviates far from the original data gradually, which may result in the loss of useful signals, like, temporal dependencies. Therefore, choosing a suitable variance schedule and diffusion steps is important to ensure that the distribution space is deviated enough without losing useful signals.
