### ISSUE TITLE
Are there any ways to inverse the pred.npy in D3VAE? 

### ISSUE THREAD

**Issue by koseoyoung** [PaddlePaddle/PaddleSpatial#313]
Hi, I'm planning to utilize the D3VAE in this repo. 

The result of prediction (pred.npy) seems normalized and there is no option to inverse the result. Are there any ways to inverse the pred.npy and get the real prediction results? 
If not, I can also make a PR. 

Thanks!

**Comment by ramber1836** [comment]
> Hi, I'm planning to utilize the D3VAE in this repo.
> 
> The result of prediction (pred.npy) seems normalized and there is no option to inverse the result. Are there any ways to inverse the pred.npy and get the real prediction results? If not, I can also make a PR.
> 
> Thanks!

No, we did not implement the reverse procedure.

**Comment by koseoyoung** [comment]
@ramber1836 I see, thanks for the clarification! 

In order for people to make use of this model to actually forecast something, I think we need the reverse procedure. 
Can you review this PR #314 to see if this is the correct way to reverse it? Thanks!
