### ISSUE TITLE
Hod to adapt framework to custom data?

### ISSUE THREAD

**Issue by gabriead** [PaddlePaddle/PaddleSpatial#320]
Hi team,
great work first of all. I would like to use your framework for the domain of sports. I have a time series data of players in regards to different parameters. How would I use the data witht the current model? In what input format does the data have to be in? Is a dataframe sufficient that is grouped by player and his parameters? Can the model be trained on the data of an entire team and then predict a parameter of a given player?
Thank's a lot in advance!

**Comment by ramber1836** [comment]
Thanks for your attention! The multivariate time series data used in our work can be found in the corresponding research work READMEs; you can follow the format of those open datasets.
