### ISSUE TITLE
提几个建议,望各位大佬采纳

### ISSUE THREAD

**Issue by yuwoyizhan** [PaddlePaddle/PaddleSpatial#4]
1.教程目前是英文的,能否提供中文版本,很简单吧.目前教程目录中的几个链接也都是英文的,希望提供中文.
2.[PaddleSpatial](https://github.com/PaddlePaddle/PaddleSpatial)仓库开设之前,我就一直跟某个飞桨大佬提议,开设时空序列预测仓库,因为我使用了easydl的时间预测序列,效果不好,说白了就是性能差,完全达不到预期,希望能有更专业的仓库,比如可以提供多种算法,easydl只需要我提供数据execl,我完全不知道内部做了什么,而且效果不怎么样.时间序列预测,应该是一个学术界研究热点,如果有一个很牛逼的时间预测序列算法,每个人都可以炒股发财了,哈哈哈哈.开个玩笑.不指望时间预测序列能预测股票,但希望,可以复现顶级论文算法,很多时间预测序列算法很牛逼的样子,似乎前景也不错,希望复现.
3.作为仓库的开发者,你们希望,输入数据,是一种怎样的组织形式呢?用execl?
4.房价预测问题,只需要弄个3层小神经网络,就可以达到很好的效果.输入是13维数组,模型输出是房价,训练时数据集得分成训练集和验证集.我想说的是,现实世界中,往往做一个实验,可以找到很多数据,输入N维数据,得到某个输出数据,比如为了研究重力和质量的关系,通过实验,得到了大量数据集,使用这些数据集是否就能得出关系呢?神经网络是否可以很好的拟合两者之间的关系呢?这个问题很简单,是正比关系,但是对于一些关系很复杂,目前不知道存在什么关系的情况下,神经网络能否很好拟合呢?举个例子,端流就很难.这也可以看出输入N维数据,输出某个结果.你们目前提供这种输入N维数据,输出某个结果的模型吗?好比房价预测问题,输入13维数据,输出房价.

**Comment by zhoujingbo** [comment]
[yuwoyizhan](https://github.com/yuwoyizhan),您好；

非常感谢对我们项目的关注，您说的几个问题我来回答下
1. 目前教程确实是以英文为主，我们后续会努力同步提供中英文版本
2. 时间序列预测也会是PaddleSpatial未来重点建设的方向，欢迎您关注。如果可行的话，也欢迎您贡献代码
3. 我们对数据输入格式没有限制，定义合适的dataloader就可以。目前看以csv文件为主吧
4. 不知道我们理解的是不是正确，感觉这个问题使用一般的DNN神经网络就可以做到。但是模型预测效果的好坏，也受到目标变量预测难易程度的限制。

再次感谢您的关注
祝好

> 1.教程目前是英文的,能否提供中文版本,很简单吧.目前教程目录中的几个链接也都是英文的,希望提供中文. 2.[PaddleSpatial](https://github.com/PaddlePaddle/PaddleSpatial)仓库开设之前,我就一直跟某个飞桨大佬提议,开设时空序列预测仓库,因为我使用了easydl的时间预测序列,效果不好,说白了就是性能差,完全达不到预期,希望能有更专业的仓库,比如可以提供多种算法,easydl只需要我提供数据execl,我完全不知道内部做了什么,而且效果不怎么样.时间序列预测,应该是一个学术界研究热点,如果有一个很牛逼的时间预测序列算法,每个人都可以炒股发财了,哈哈哈哈.开个玩笑.不指望时间预测序列能预测股票,但希望,可以复现顶级论文算法,很多时间预测序列算法很牛逼的样子,似乎前景也不错,希望复现. 3.作为仓库的开发者,你们希望,输入数据,是一种怎样的组织形式呢?用execl? 4.房价预测问题,只需要弄个3层小神经网络,就可以达到很好的效果.输入是13维数组,模型输出是房价,训练时数据集得分成训练集和验证集.我想说的是,现实世界中,往往做一个实验,可以找到很多数据,输入N维数据,得到某个输出数据,比如为了研究重力和质量的关系,通过实验,得到了大量数据集,使用这些数据集是否就能得出关系呢?神经网络是否可以很好的拟合两者之间的关系呢?这个问题很简单,是正比关系,但是对于一些关系很复杂,目前不知道存在什么关系的情况下,神经网络能否很好拟合呢?举个例子,端流就很难.这也可以看出输入N维数据,输出某个结果.你们目前提供这种输入N维数据,输出某个结果的模型吗?好比房价预测问题,输入13维数据,输出房价.

**Comment by yuwoyizhan** [comment]
1.关于第二个问题,时间预测序列,我想问问,你们打算提供什么算法或者模型呢?比如对于预测股票价格这个目标变量,你们提供的算法或者模型,需要飞桨使用者提供过去一年(也就是很长时间)的股票价格还是过去一个星期(最近一段时间)的股票价格?我需要提供股票每日的成交量,最高价,最低价等自变量,还是只需要提供股票价格这个变量的相关数据?也就是说是不是为了预测某个变量,只需要提供该变量过去的数值数据,而不需要提供其他数据了?
2.关于第四个问题,房价预测问题中,数据量非常少,而且通过13个自变量,来预测房价这个因变量.我想问的是,如何通过一个算法或者模型,知道房价这个自变量是受哪些因变量影响和决定的?我在提供数据给算法或者模型训练之前,我肯定需要知道房价究竟由哪些自变量决定吧.那些跟房价无关的的自变量也就不用输入神经网络训练了.
以上这些问题,望各位大佬仔细回答一下,谢谢.就算是个人想法或者经验之谈,也好.
@zhoujingbo

**Comment by zhoujingbo** [comment]
> 1.关于第二个问题,时间预测序列,我想问问,你们打算提供什么算法或者模型呢?比如对于预测股票价格这个目标变量,你们提供的算法或者模型,需要飞桨使用者提供过去一年(也就是很长时间)的股票价格还是过去一个星期(最近一段时间)的股票价格?我需要提供股票每日的成交量,最高价,最低价等自变量,还是只需要提供股票价格这个变量的相关数据?也就是说是不是为了预测某个变量,只需要提供该变量过去的数值数据,而不需要提供其他数据了? 2.关于第四个问题,房价预测问题中,数据量非常少,而且通过13个自变量,来预测房价这个因变量.我想问的是,如何通过一个算法或者模型,知道房价这个自变量是受哪些因变量影响和决定的?我在提供数据给算法或者模型训练之前,我肯定需要知道房价究竟由哪些自变量决定吧.那些跟房价无关的的自变量也就不用输入神经网络训练了. 以上这些问题,望各位大佬仔细回答一下,谢谢.就算是个人想法或者经验之谈,也好. @zhoujingbo

您好；
1）时间序列预测问题有很多不同的方法和模型，是一个很广很深的领域，这个我们也在逐渐学习和构建。我觉得总体来讲，应该提供的对Y值预测有帮助的X变量越多越好。
2）对于哪些自变量受影响，可以用各种各样的特征选择（feature selection）的方法，比如先计算自变量和应变量的相关性等方法。
已加您微信，可以线下互相多交流讨论，谢谢。
祝好
