### ISSUE TITLE
现在leaderboard 的结果是需要提交代码的吗....confusing.....

### ISSUE THREAD

**Issue by perveil** [PaddlePaddle/PaddleSpatial#77]
![image](https://user-images.githubusercontent.com/29778965/169195329-5f2c3124-12cb-477a-90a0-9bb60c55163b.png)
 想问一下当前提交的结果是根据给的245 的最后15天，然后预测未来两天的结果吗？

**Comment by ramber1836** [comment]
Please refer to the new version of the report.

Regards,
Xinjiang Lu

**Comment by mb-Ma** [comment]
This mode is very strange. And we do not know the online test_x's file name. There is only "/test_x" in official code. Did you run it without an error (read_csv(path))?

**Comment by zhoujingbo** [comment]
Hi,
You can follow the Evaluation Manual.  If you follow the instructions, it should be OK to submit your model. 

Regards
