### ISSUE TITLE
'NoneType' object has no attribute 'forecast'

### ISSUE THREAD

**Issue by q3erf** [PaddlePaddle/PaddleSpatial#85]
hi, when I use base environment, I  got error like this, 'NoneType' object has no attribute 'forecast'. 
But I did define the correct predict.py and prepare.py files, and I can run "python evaluation.py" locally to get the results on my server.

**Comment by ramber1836** [comment]
Hi, there,

You can provide your team name and the administrator will reply to you in a
couple of days (the workload is hard) by checking the online test log.
Thanks for your understanding.

Regards,
Xinjiang Lu

**Comment by q3erf** [comment]
thank you！

**Comment by q3erf** [comment]
I found this error may be caused by lightgbm in base environment, and I open another issue about this #87

**Comment by q3erf** [comment]
已收到，我将尽快回复
