### ISSUE TITLE
lightgbm maybe not correctly installed in base environment

### ISSUE THREAD

**Issue by q3erf** [PaddlePaddle/PaddleSpatial#87]
At the beginning, I found that it would appear `'NoneType' object has no attribute 'forecast'` when using lightgbm in the base environment, and  After commenting `import lightgbm as lgb`, this error is solved. could you please check the base environment whether lightgbm is installed correctly. thank you!

**Comment by ramber1836** [comment]
We will check it ASAP.
Thanks.

Regards,
Xinjiang Lu

**Comment by q3erf** [comment]
已收到，我将尽快回复

**Comment by ramber1836** [comment]
Problem solved.
You can check it now.

Regards,
Xinjiang Lu

**Comment by q3erf** [comment]
Thanks!
